#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/env.sh"

load_operation_portal_env() {
  local env_file="${OPERATION_PORTAL_ENV_FILE:-$CONF_DIR/operation-portal.env}"

  if [ -f "$env_file" ]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_file"
    set +a
  fi

  export OPERATION_PORTAL_ENV_FILE="$env_file"
}

normalize_operation_portal_defaults() {
  OPERATION_PORTAL_PORT="${OPERATION_PORTAL_PORT:-8003}"
  OPERATION_PORTAL_FRONTEND_ENDPOINT="${OPERATION_PORTAL_FRONTEND_ENDPOINT:-http://127.0.0.1:$OPERATION_PORTAL_PORT}"
  OPERATION_PORTAL_REPORT_PAGE_SIZE="${OPERATION_PORTAL_REPORT_PAGE_SIZE:-100000}"

  OPERATION_PORTAL_VAULT_CONTAINER="${OPERATION_PORTAL_VAULT_CONTAINER:-local-operation-portal-vault}"
  OPERATION_PORTAL_VAULT_IMAGE="${OPERATION_PORTAL_VAULT_IMAGE:-hashicorp/vault:1.15}"
  OPERATION_PORTAL_VAULT_ADDR="${OPERATION_PORTAL_VAULT_ADDR:-http://127.0.0.1:8200}"
  OPERATION_PORTAL_VAULT_TOKEN="${OPERATION_PORTAL_VAULT_TOKEN:-root-token}"
  OPERATION_PORTAL_ENGINE_PATH="${OPERATION_PORTAL_ENGINE_PATH:-operation_portal}"

  OPERATION_PORTAL_REDIS_URL="${OPERATION_PORTAL_REDIS_URL:-redis://127.0.0.1:6379}"

  OPERATION_PORTAL_DB_HOST="${OPERATION_PORTAL_DB_HOST:-127.0.0.1}"
  OPERATION_PORTAL_DB_PORT="${OPERATION_PORTAL_DB_PORT:-3306}"
  OPERATION_PORTAL_DB_NAME="${OPERATION_PORTAL_DB_NAME:-operation_portal}"
  OPERATION_PORTAL_DB_USERNAME="${OPERATION_PORTAL_DB_USERNAME:-operation_portal_jdbc}"
  OPERATION_PORTAL_DB_PASSWORD="${OPERATION_PORTAL_DB_PASSWORD:-password}"
  OPERATION_PORTAL_DB_READ_USERNAME="${OPERATION_PORTAL_DB_READ_USERNAME:-operation_portal_ro}"
  OPERATION_PORTAL_DB_READ_PASSWORD="${OPERATION_PORTAL_DB_READ_PASSWORD:-password}"
  OPERATION_PORTAL_DB_FLYWAY_USERNAME="${OPERATION_PORTAL_DB_FLYWAY_USERNAME:-root}"
  OPERATION_PORTAL_DB_FLYWAY_PASSWORD="${OPERATION_PORTAL_DB_FLYWAY_PASSWORD:-}"
  OPERATION_PORTAL_DB_POOL_MIN="${OPERATION_PORTAL_DB_POOL_MIN:-5}"
  OPERATION_PORTAL_DB_POOL_MAX="${OPERATION_PORTAL_DB_POOL_MAX:-10}"

  OPERATION_PORTAL_HUB_DB_HOST="${OPERATION_PORTAL_HUB_DB_HOST:-127.0.0.1}"
  OPERATION_PORTAL_HUB_DB_PORT="${OPERATION_PORTAL_HUB_DB_PORT:-3306}"
  OPERATION_PORTAL_HUB_DB_NAME="${OPERATION_PORTAL_HUB_DB_NAME:-central_ledger}"
  OPERATION_PORTAL_HUB_DB_USERNAME="${OPERATION_PORTAL_HUB_DB_USERNAME:-central_ledger}"
  OPERATION_PORTAL_HUB_DB_PASSWORD="${OPERATION_PORTAL_HUB_DB_PASSWORD:-password}"
  OPERATION_PORTAL_HUB_DB_POOL_MIN="${OPERATION_PORTAL_HUB_DB_POOL_MIN:-5}"
  OPERATION_PORTAL_HUB_DB_POOL_MAX="${OPERATION_PORTAL_HUB_DB_POOL_MAX:-10}"

  OPERATION_PORTAL_MONGO_URI="${OPERATION_PORTAL_MONGO_URI:-mongodb://127.0.0.1:27017}"
  OPERATION_PORTAL_MONGO_DATABASE="${OPERATION_PORTAL_MONGO_DATABASE:-reporting}"
  OPERATION_PORTAL_MONGO_READ_PREFERENCE="${OPERATION_PORTAL_MONGO_READ_PREFERENCE:-primary}"

  OPERATION_PORTAL_S3_ENABLED="${OPERATION_PORTAL_S3_ENABLED:-false}"
  OPERATION_PORTAL_S3_BUCKET="${OPERATION_PORTAL_S3_BUCKET:-local-operation-portal}"
  OPERATION_PORTAL_S3_ACCESS_KEY="${OPERATION_PORTAL_S3_ACCESS_KEY:-placeholder}"
  OPERATION_PORTAL_S3_SECRET_KEY="${OPERATION_PORTAL_S3_SECRET_KEY:-placeholder}"
  OPERATION_PORTAL_S3_REGION="${OPERATION_PORTAL_S3_REGION:-us-east-1}"
  OPERATION_PORTAL_S3_PREFIX="${OPERATION_PORTAL_S3_PREFIX:-reports/}"
  OPERATION_PORTAL_S3_ENDPOINT="${OPERATION_PORTAL_S3_ENDPOINT:-}"
  OPERATION_PORTAL_S3_PATH_STYLE_ACCESS="${OPERATION_PORTAL_S3_PATH_STYLE_ACCESS:-true}"
  OPERATION_PORTAL_S3_PRESIGNED_URL_LIFETIME="${OPERATION_PORTAL_S3_PRESIGNED_URL_LIFETIME:-PT15M}"

  OPERATION_PORTAL_PID_FILE="$RUN_DIR/operation-portal.pid"
  OPERATION_PORTAL_LOG_FILE="$LOG_DIR/operation-portal.log"
  OPERATION_PORTAL_JAR="$OPERATION_PORTAL_HOME/implementation/web_api_operation/target/operation_api.jar"

  export OPERATION_PORTAL_PORT OPERATION_PORTAL_FRONTEND_ENDPOINT OPERATION_PORTAL_REPORT_PAGE_SIZE
  export OPERATION_PORTAL_VAULT_CONTAINER OPERATION_PORTAL_VAULT_IMAGE OPERATION_PORTAL_VAULT_ADDR OPERATION_PORTAL_VAULT_TOKEN OPERATION_PORTAL_ENGINE_PATH
  export OPERATION_PORTAL_REDIS_URL
  export OPERATION_PORTAL_DB_HOST OPERATION_PORTAL_DB_PORT OPERATION_PORTAL_DB_NAME OPERATION_PORTAL_DB_USERNAME OPERATION_PORTAL_DB_PASSWORD
  export OPERATION_PORTAL_DB_READ_USERNAME OPERATION_PORTAL_DB_READ_PASSWORD OPERATION_PORTAL_DB_FLYWAY_USERNAME OPERATION_PORTAL_DB_FLYWAY_PASSWORD
  export OPERATION_PORTAL_DB_POOL_MIN OPERATION_PORTAL_DB_POOL_MAX
  export OPERATION_PORTAL_HUB_DB_HOST OPERATION_PORTAL_HUB_DB_PORT OPERATION_PORTAL_HUB_DB_NAME OPERATION_PORTAL_HUB_DB_USERNAME OPERATION_PORTAL_HUB_DB_PASSWORD
  export OPERATION_PORTAL_HUB_DB_POOL_MIN OPERATION_PORTAL_HUB_DB_POOL_MAX
  export OPERATION_PORTAL_MONGO_URI OPERATION_PORTAL_MONGO_DATABASE OPERATION_PORTAL_MONGO_READ_PREFERENCE
  export OPERATION_PORTAL_S3_ENABLED OPERATION_PORTAL_S3_BUCKET OPERATION_PORTAL_S3_ACCESS_KEY OPERATION_PORTAL_S3_SECRET_KEY
  export OPERATION_PORTAL_S3_REGION OPERATION_PORTAL_S3_PREFIX OPERATION_PORTAL_S3_ENDPOINT OPERATION_PORTAL_S3_PATH_STYLE_ACCESS OPERATION_PORTAL_S3_PRESIGNED_URL_LIFETIME
  export OPERATION_PORTAL_PID_FILE OPERATION_PORTAL_LOG_FILE OPERATION_PORTAL_JAR
}

operation_portal_init() {
  load_operation_portal_env
  normalize_operation_portal_defaults

  if [ ! -f "$OPERATION_PORTAL_HOME/implementation/pom.xml" ]; then
    echo "Missing ml-operation-portal repo: $OPERATION_PORTAL_HOME" >&2
    exit 1
  fi
}
