#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/env.sh"

ENV_FILE="$CONF_DIR/wallet1-pivotal.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing wallet1 env file: $ENV_FILE" >&2
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

: "${DB_WRITE_HOST:=127.0.0.1}"
: "${DB_WRITE_PORT:=3306}"
: "${DB_WRITE_USERNAME:=pivotal}"
: "${DB_WRITE_PASSWORD:=password}"
: "${DB_WRITE_NAME:=pivotal}"
: "${DB_READ_HOST:=$DB_WRITE_HOST}"
: "${DB_READ_PORT:=$DB_WRITE_PORT}"
: "${DB_READ_USERNAME:=$DB_WRITE_USERNAME}"
: "${DB_READ_PASSWORD:=$DB_WRITE_PASSWORD}"
: "${DB_READ_NAME:=$DB_WRITE_NAME}"
: "${CENTRAL_LEDGER_URL:=http://localhost:3001}"
: "${WEB_PIVOTAL_PORT:=3202}"
: "${PIVOTAL_PORTAL_PORT:=4173}"
: "${VITE_WEB_PIVOTAL_API_BASE_URL:=http://localhost:${WEB_PIVOTAL_PORT}}"
: "${PIVOTAL_IAM_JWT_SECRET:=${IAM_JWT_SECRET:-local-pivotal-iam-secret}}"
: "${PIVOTAL_IAM_ADMIN_SEED_EMAIL:=admin@pivotal.local}"
: "${PIVOTAL_IAM_ADMIN_SEED_TEMP_PASSWORD:=${IAM_BOOTSTRAP_ADMIN_PASSWORD:-admin12345}}"
: "${PIVOTAL_IAM_CORS_ALLOWED_ORIGINS:=http://localhost:${PIVOTAL_PORTAL_PORT},http://127.0.0.1:${PIVOTAL_PORTAL_PORT},http://localhost:5173,http://127.0.0.1:5173}"
: "${PIVOTAL_IAM_ACCESS_TOKEN_TTL_SECONDS:=${IAM_ACCESS_TOKEN_TTL_SECONDS:-3600}}"
: "${REPORT_S3_ENABLED:=true}"
: "${REPORT_S3_BUCKET:=pivotal-reports}"
: "${REPORT_S3_REGION:=us-east-1}"
: "${REPORT_S3_ACCESS_KEY_ID:=minioadmin}"
: "${REPORT_S3_SECRET_ACCESS_KEY:=minioadmin}"
: "${REPORT_S3_ENDPOINT:=http://127.0.0.1:9000}"
: "${REPORT_S3_FORCE_PATH_STYLE:=true}"
: "${REPORT_S3_PREFIX:=reports/}"
: "${REPORT_S3_PRESIGNED_URL_TTL_SECONDS:=900}"
: "${WEB_PIVOTAL_REPORT_DOWNLOAD_WORKER_ENABLED:=false}"
: "${REPORT_DOWNLOAD_WORKER_ENABLED:=true}"
: "${REPORT_DOWNLOAD_POLL_INTERVAL_MS:=5000}"
: "${REPORT_DOWNLOAD_PAGE_SIZE:=50000}"
: "${REPORT_DOWNLOAD_MAX_ROWS_PER_FILE:=50000}"
: "${REPORT_DOWNLOAD_MAX_ZIP_FILES:=1}"
: "${REPORT_DOWNLOAD_MAX_CONCURRENT:=3}"
: "${REPORT_DOWNLOAD_STALE_RUNNING_TTL_MS:=1200000}"
: "${REDIS_URL:=redis://127.0.0.1:6379}"
: "${ACCESS_JWT_ENABLED:=false}"
: "${REDIS_CACHE_ITEM_TIMEOUT_MS:=900000}"
: "${FSPIOP_SOCKET_TIMEOUT_MS:=30000}"
: "${FSPIOP_CONNECTION_TIMEOUT_MS:=5000}"
: "${FSPIOP_TLS_VERIFY_SERVER_CERT:=false}"
: "${FSPIOP_TLS_VERIFY_DOMAIN:=false}"
: "${PREFIX_ORACLE_ENDPOINT:=http://127.0.0.1:${WEB_PIVOTAL_PORT}}"
: "${PREFIX_ORACLE_CACHE_TTL_MS:=300000}"
: "${CONNECTOR_ILP_SECRET:=wallet1-ilp-secret}"
: "${CATALYST_URL:=http://localhost:8081}"
: "${DEMOWALLET_URL:=http://127.0.0.1:8081}"
: "${DEMOWALLET_SOCKET_TIMEOUT_MS:=30000}"
: "${DEMOWALLET_CONNECTION_TIMEOUT_MS:=5000}"
: "${PIVOTAL_AUDIT_STREAM_NAME:=PIVOTAL_AUDIT}"

cat > "$PIVOTAL_HOME/packages/apps/app-auditor/.env" <<EOF
NATS_URL=${NATS_URL}
PIVOTAL_AUDIT_STREAM_NAME=${PIVOTAL_AUDIT_STREAM_NAME}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
EOF

cat > "$PIVOTAL_HOME/packages/apps/web-inbound/.env" <<EOF
WEB_INBOUND_PORT=${WEB_INBOUND_PORT}
NATS_URL=${NATS_URL}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
CENTRAL_LEDGER_URL=${CENTRAL_LEDGER_URL}
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
EOF

cat > "$PIVOTAL_HOME/packages/apps/web-outbound/.env" <<EOF
WEB_OUTBOUND_PORT=${WEB_OUTBOUND_PORT}
PARTICIPANT_KEY_STORE_REFRESH_INTERVAL_SECONDS=5
NATS_URL=${NATS_URL}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
REDIS_URL=${REDIS_URL}
ACCESS_JWT_ENABLED=${ACCESS_JWT_ENABLED}
REDIS_CACHE_ITEM_TIMEOUT_MS=${REDIS_CACHE_ITEM_TIMEOUT_MS}
CENTRAL_LEDGER_URL=${CENTRAL_LEDGER_URL}
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
FSPIOP_SOCKET_TIMEOUT_MS=${FSPIOP_SOCKET_TIMEOUT_MS}
FSPIOP_CONNECTION_TIMEOUT_MS=${FSPIOP_CONNECTION_TIMEOUT_MS}
FSPIOP_TLS_VERIFY_SERVER_CERT=${FSPIOP_TLS_VERIFY_SERVER_CERT}
FSPIOP_TLS_VERIFY_DOMAIN=${FSPIOP_TLS_VERIFY_DOMAIN}
PREFIX_ORACLE_ENDPOINT=${PREFIX_ORACLE_ENDPOINT}
PREFIX_ORACLE_CACHE_TTL_MS=${PREFIX_ORACLE_CACHE_TTL_MS}
EOF

cat > "$PIVOTAL_HOME/packages/apps/web-pivotal/.env" <<EOF
WEB_PIVOTAL_PORT=${WEB_PIVOTAL_PORT}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
CENTRAL_LEDGER_URL=${CENTRAL_LEDGER_URL}
PIVOTAL_IAM_JWT_SECRET=${PIVOTAL_IAM_JWT_SECRET}
PIVOTAL_IAM_ADMIN_SEED_EMAIL=${PIVOTAL_IAM_ADMIN_SEED_EMAIL}
PIVOTAL_IAM_ADMIN_SEED_TEMP_PASSWORD=${PIVOTAL_IAM_ADMIN_SEED_TEMP_PASSWORD}
PIVOTAL_IAM_CORS_ALLOWED_ORIGINS=${PIVOTAL_IAM_CORS_ALLOWED_ORIGINS}
PIVOTAL_IAM_ACCESS_TOKEN_TTL_SECONDS=${PIVOTAL_IAM_ACCESS_TOKEN_TTL_SECONDS}
REPORT_DOWNLOAD_WORKER_ENABLED=${WEB_PIVOTAL_REPORT_DOWNLOAD_WORKER_ENABLED}
REPORT_S3_ENABLED=${REPORT_S3_ENABLED}
REPORT_S3_BUCKET=${REPORT_S3_BUCKET}
REPORT_S3_REGION=${REPORT_S3_REGION}
REPORT_S3_ACCESS_KEY_ID=${REPORT_S3_ACCESS_KEY_ID}
REPORT_S3_SECRET_ACCESS_KEY=${REPORT_S3_SECRET_ACCESS_KEY}
REPORT_S3_ENDPOINT=${REPORT_S3_ENDPOINT}
REPORT_S3_FORCE_PATH_STYLE=${REPORT_S3_FORCE_PATH_STYLE}
REPORT_S3_PREFIX=${REPORT_S3_PREFIX}
REPORT_S3_PRESIGNED_URL_TTL_SECONDS=${REPORT_S3_PRESIGNED_URL_TTL_SECONDS}
EOF

mkdir -p "$PIVOTAL_HOME/packages/apps/report-worker"
cat > "$PIVOTAL_HOME/packages/apps/report-worker/.env" <<EOF
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
REPORT_DOWNLOAD_WORKER_ENABLED=${REPORT_DOWNLOAD_WORKER_ENABLED}
REPORT_DOWNLOAD_POLL_INTERVAL_MS=${REPORT_DOWNLOAD_POLL_INTERVAL_MS}
REPORT_DOWNLOAD_PAGE_SIZE=${REPORT_DOWNLOAD_PAGE_SIZE}
REPORT_DOWNLOAD_MAX_ROWS_PER_FILE=${REPORT_DOWNLOAD_MAX_ROWS_PER_FILE}
REPORT_DOWNLOAD_MAX_ZIP_FILES=${REPORT_DOWNLOAD_MAX_ZIP_FILES}
REPORT_DOWNLOAD_MAX_CONCURRENT=${REPORT_DOWNLOAD_MAX_CONCURRENT}
REPORT_DOWNLOAD_STALE_RUNNING_TTL_MS=${REPORT_DOWNLOAD_STALE_RUNNING_TTL_MS}
REPORT_S3_ENABLED=${REPORT_S3_ENABLED}
REPORT_S3_BUCKET=${REPORT_S3_BUCKET}
REPORT_S3_REGION=${REPORT_S3_REGION}
REPORT_S3_ACCESS_KEY_ID=${REPORT_S3_ACCESS_KEY_ID}
REPORT_S3_SECRET_ACCESS_KEY=${REPORT_S3_SECRET_ACCESS_KEY}
REPORT_S3_ENDPOINT=${REPORT_S3_ENDPOINT}
REPORT_S3_FORCE_PATH_STYLE=${REPORT_S3_FORCE_PATH_STYLE}
REPORT_S3_PREFIX=${REPORT_S3_PREFIX}
REPORT_S3_PRESIGNED_URL_TTL_SECONDS=${REPORT_S3_PRESIGNED_URL_TTL_SECONDS}
EOF

cat > "$PIVOTAL_HOME/packages/portal/.env" <<EOF
PIVOTAL_PORTAL_PORT=${PIVOTAL_PORTAL_PORT}
VITE_WEB_PIVOTAL_API_BASE_URL=${VITE_WEB_PIVOTAL_API_BASE_URL}
EOF

cat > "$PIVOTAL_HOME/packages/samples/wallet1-connector/.env" <<EOF
NATS_URL=${NATS_URL}
PIVOTAL_FSPIOP_STREAM_NAME=PIVOTAL_FSPIOP
PIVOTAL_AUDIT_STREAM_NAME=PIVOTAL_AUDIT
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
FSPIOP_SOCKET_TIMEOUT_MS=${FSPIOP_SOCKET_TIMEOUT_MS}
FSPIOP_CONNECTION_TIMEOUT_MS=${FSPIOP_CONNECTION_TIMEOUT_MS}
FSPIOP_TLS_VERIFY_SERVER_CERT=${FSPIOP_TLS_VERIFY_SERVER_CERT}
FSPIOP_TLS_VERIFY_DOMAIN=${FSPIOP_TLS_VERIFY_DOMAIN}
CONNECTOR_ID=${CONNECTOR_ID}
CONNECTOR_SUPPORTED_CURRENCIES=${CONNECTOR_SUPPORTED_CURRENCIES}
CONNECTOR_ILP_SECRET=${CONNECTOR_ILP_SECRET}
CATALYST_URL=${CATALYST_URL}
CATALYST_ENGINE_MODE=${CATALYST_ENGINE_MODE}
DEMOWALLET_URL=${DEMOWALLET_URL}
DEMOWALLET_SOCKET_TIMEOUT_MS=${DEMOWALLET_SOCKET_TIMEOUT_MS}
DEMOWALLET_CONNECTION_TIMEOUT_MS=${DEMOWALLET_CONNECTION_TIMEOUT_MS}
EOF
