#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/env.sh"

ENV_FILE="$CONF_DIR/wallet1-pivotal.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing wallet1 env file: $ENV_FILE" >&2
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

: "${DB_WRITE_HOST:=127.0.0.1}"
: "${DB_WRITE_PORT:=3306}"
: "${DB_WRITE_USERNAME:=pivotal}"
: "${DB_WRITE_PASSWORD:=password}"
: "${DB_WRITE_NAME:=pivotal}"
: "${DB_READ_HOST:=$DB_WRITE_HOST}"
: "${DB_READ_PORT:=$DB_WRITE_PORT}"
: "${DB_READ_USERNAME:=$DB_WRITE_USERNAME}"
: "${DB_READ_PASSWORD:=$DB_WRITE_PASSWORD}"
: "${DB_READ_NAME:=$DB_WRITE_NAME}"
: "${CENTRAL_LEDGER_URL:=http://localhost:3001}"
: "${REDIS_URL:=redis://127.0.0.1:6379}"
: "${REDIS_CACHE_ITEM_TIMEOUT_MS:=900000}"
: "${FSPIOP_SOCKET_TIMEOUT_MS:=30000}"
: "${FSPIOP_CONNECTION_TIMEOUT_MS:=5000}"
: "${FSPIOP_TLS_VERIFY_SERVER_CERT:=false}"
: "${FSPIOP_TLS_VERIFY_DOMAIN:=false}"
: "${CONNECTOR_ILP_SECRET:=wallet1-ilp-secret}"
: "${CATALYST_URL:=http://localhost:8081}"
: "${DEMOWALLET_URL:=http://127.0.0.1:8081}"
: "${DEMOWALLET_SOCKET_TIMEOUT_MS:=30000}"
: "${DEMOWALLET_CONNECTION_TIMEOUT_MS:=5000}"
: "${PIVOTAL_AUDIT_STREAM_NAME:=PIVOTAL_AUDIT}"

cat > "$PIVOTAL_HOME/packages/apps/app-auditor/.env" <<EOF
NATS_URL=${NATS_URL}
PIVOTAL_AUDIT_STREAM_NAME=${PIVOTAL_AUDIT_STREAM_NAME}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
EOF

cat > "$PIVOTAL_HOME/packages/apps/web-inbound/.env" <<EOF
WEB_INBOUND_PORT=${WEB_INBOUND_PORT}
NATS_URL=${NATS_URL}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
CENTRAL_LEDGER_URL=${CENTRAL_LEDGER_URL}
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
EOF

cat > "$PIVOTAL_HOME/packages/apps/web-outbound/.env" <<EOF
WEB_OUTBOUND_PORT=${WEB_OUTBOUND_PORT}
PARTICIPANT_KEY_STORE_REFRESH_INTERVAL_SECONDS=5
NATS_URL=${NATS_URL}
DB_WRITE_HOST=${DB_WRITE_HOST}
DB_WRITE_PORT=${DB_WRITE_PORT}
DB_WRITE_USERNAME=${DB_WRITE_USERNAME}
DB_WRITE_PASSWORD=${DB_WRITE_PASSWORD}
DB_WRITE_NAME=${DB_WRITE_NAME}
DB_READ_HOST=${DB_READ_HOST}
DB_READ_PORT=${DB_READ_PORT}
DB_READ_USERNAME=${DB_READ_USERNAME}
DB_READ_PASSWORD=${DB_READ_PASSWORD}
DB_READ_NAME=${DB_READ_NAME}
REDIS_URL=${REDIS_URL}
REDIS_CACHE_ITEM_TIMEOUT_MS=${REDIS_CACHE_ITEM_TIMEOUT_MS}
CENTRAL_LEDGER_URL=${CENTRAL_LEDGER_URL}
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
FSPIOP_SOCKET_TIMEOUT_MS=${FSPIOP_SOCKET_TIMEOUT_MS}
FSPIOP_CONNECTION_TIMEOUT_MS=${FSPIOP_CONNECTION_TIMEOUT_MS}
FSPIOP_TLS_VERIFY_SERVER_CERT=${FSPIOP_TLS_VERIFY_SERVER_CERT}
FSPIOP_TLS_VERIFY_DOMAIN=${FSPIOP_TLS_VERIFY_DOMAIN}
EOF

cat > "$PIVOTAL_HOME/packages/samples/wallet1-connector/.env" <<EOF
NATS_URL=${NATS_URL}
PIVOTAL_FSPIOP_STREAM_NAME=PIVOTAL_FSPIOP
PIVOTAL_AUDIT_STREAM_NAME=PIVOTAL_AUDIT
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
FSPIOP_SOCKET_TIMEOUT_MS=${FSPIOP_SOCKET_TIMEOUT_MS}
FSPIOP_CONNECTION_TIMEOUT_MS=${FSPIOP_CONNECTION_TIMEOUT_MS}
FSPIOP_TLS_VERIFY_SERVER_CERT=${FSPIOP_TLS_VERIFY_SERVER_CERT}
FSPIOP_TLS_VERIFY_DOMAIN=${FSPIOP_TLS_VERIFY_DOMAIN}
CONNECTOR_ID=${CONNECTOR_ID}
CONNECTOR_SUPPORTED_CURRENCIES=${CONNECTOR_SUPPORTED_CURRENCIES}
CONNECTOR_ILP_SECRET=${CONNECTOR_ILP_SECRET}
CATALYST_URL=${CATALYST_URL}
CATALYST_ENGINE_MODE=${CATALYST_ENGINE_MODE}
DEMOWALLET_URL=${DEMOWALLET_URL}
DEMOWALLET_SOCKET_TIMEOUT_MS=${DEMOWALLET_SOCKET_TIMEOUT_MS}
DEMOWALLET_CONNECTION_TIMEOUT_MS=${DEMOWALLET_CONNECTION_TIMEOUT_MS}
EOF
