#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/env.sh"

ENV_FILE="$CONF_DIR/wallet1-mtpa.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing wallet1 env file: $ENV_FILE" >&2
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

cat > "$ROOT_DIR/mtpa/packages/apps/web-inbound/.env" <<EOF
WEB_INBOUND_PORT=${WEB_INBOUND_PORT}
NATS_URL=${NATS_URL}
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
EOF

cat > "$ROOT_DIR/mtpa/packages/apps/web-outbound/.env" <<EOF
WEB_OUTBOUND_PORT=${WEB_OUTBOUND_PORT}
NATS_URL=${NATS_URL}
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
EOF

cat > "$ROOT_DIR/mtpa/packages/samples/wallet1-connector/.env" <<EOF
NATS_URL=${NATS_URL}
PAYPORT_FSPIOP_STREAM_NAME=PAYPORT_FSPIOP
FSPIOP_PARTIES_URL=${FSPIOP_PARTIES_URL}
FSPIOP_QUOTES_URL=${FSPIOP_QUOTES_URL}
FSPIOP_TRANSFERS_URL=${FSPIOP_TRANSFERS_URL}
FSPIOP_SWITCH_ID=${FSPIOP_SWITCH_ID}
FSPIOP_USE_JWS=${FSPIOP_USE_JWS}
FSPIOP_USE_MUTUAL_TLS=${FSPIOP_USE_MUTUAL_TLS}
FSPIOP_TLS_VERIFY_SERVER_CERT=false
FSPIOP_TLS_VERIFY_DOMAIN=false
CONNECTOR_ID=${CONNECTOR_ID}
CONNECTOR_SUPPORTED_CURRENCIES=${CONNECTOR_SUPPORTED_CURRENCIES}
CATALYST_ENGINE_MODE=${CATALYST_ENGINE_MODE}
EOF
